import { useEffect, useState } from 'react'
import {
  History,
  RefreshCw,
  TrendingUp,
  TrendingDown,
  Brain,
  BarChart3,
  Activity,
} from 'lucide-react'
import api from '../services/api'

export default function PredictionHistory() {
  const [history, setHistory] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const loadHistory = async () => {
    setLoading(true)
    setError('')

    try {
      const response = await api.get('/api/prediction/history')

      setHistory(response.data.data || [])
    } catch (err) {
      setError(
        err.response?.data?.detail ||
        'Unable to load prediction history.'
      )
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadHistory()
  }, [])

  const formatDate = (date) => {
    if (!date) return '-'

    return new Date(date).toLocaleString('en-IN', {
      dateStyle: 'medium',
      timeStyle: 'short',
    })
  }

  const formatNumber = (value, decimals = 2) => {
    const number = Number(value)

    if (!Number.isFinite(number)) return '-'

    return number.toLocaleString('en-IN', {
      maximumFractionDigits: decimals,
    })
  }

  return (
    <div className="space-y-6">

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">

        <div className="flex items-center gap-3">

          <div className="w-11 h-11 rounded-xl bg-accent-blue/10 border border-accent-blue/30 flex items-center justify-center">
            <History
              size={22}
              className="text-accent-blue"
            />
          </div>

          <div>
            <h1 className="text-2xl font-bold text-white">
              Prediction History
            </h1>

            <p className="text-slate-400 text-sm mt-1">
              Review your previous AI stock predictions.
            </p>
          </div>

        </div>

        <button
          onClick={loadHistory}
          disabled={loading}
          className="btn-secondary"
        >
          <RefreshCw
            size={16}
            className={loading ? 'animate-spin' : ''}
          />
          Refresh
        </button>

      </div>

      {/* Error */}
      {error && (
        <div className="card p-5 border border-accent-red/30">
          <p className="text-accent-red text-sm">
            {error}
          </p>
        </div>
      )}

      {/* Stats */}
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">

        <div className="card card-hover p-5">
          <p className="text-xs text-slate-400">
            Total Predictions
          </p>

          <p className="text-2xl font-bold text-white mt-2">
            {loading ? 'Loading...' : history.length}
          </p>
        </div>

        <div className="card card-hover p-5">
          <p className="text-xs text-slate-400">
            UP Predictions
          </p>

          <p className="text-2xl font-bold text-accent-green mt-2">
            {loading
              ? 'Loading...'
              : history.filter(
                  (item) => item.prediction === 'UP'
                ).length}
          </p>
        </div>

        <div className="card card-hover p-5">
          <p className="text-xs text-slate-400">
            DOWN Predictions
          </p>

          <p className="text-2xl font-bold text-accent-red mt-2">
            {loading
              ? 'Loading...'
              : history.filter(
                  (item) => item.prediction === 'DOWN'
                ).length}
          </p>
        </div>

      </div>

      {/* History */}
      <div className="card p-6">

        <div className="mb-5">
          <h2 className="text-lg font-semibold text-white">
            Previous Predictions
          </h2>

          <p className="text-slate-500 text-xs mt-1">
            Predictions generated by the Random Forest model.
          </p>
        </div>

        {loading ? (

          <div className="space-y-3">
            {[1, 2, 3].map((item) => (
              <div
                key={item}
                className="h-40 rounded-xl bg-white/5 animate-pulse"
              />
            ))}
          </div>

        ) : history.length === 0 ? (

          <div className="rounded-xl border border-dashed border-white/10 p-10 text-center">

            <History
              size={36}
              className="mx-auto text-slate-500 mb-3"
            />

            <p className="text-slate-400 text-sm">
              No prediction history yet.
            </p>

            <p className="text-slate-500 text-xs mt-1">
              Generate an AI prediction to see it here.
            </p>

          </div>

        ) : (

          <div className="space-y-4">

            {history.map((item) => {

              const isUp = item.prediction === 'UP'
              const features = item.features || {}

              return (
                <div
                  key={item.id}
                  className="rounded-xl border border-white/5 bg-white/[0.02] p-5"
                >

                  {/* Main row */}
                  <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5">

                    {/* Prediction */}
                    <div className="flex items-center gap-4">

                      <div
                        className={`w-12 h-12 rounded-xl flex items-center justify-center ${
                          isUp
                            ? 'bg-accent-green/10'
                            : 'bg-accent-red/10'
                        }`}
                      >
                        {isUp ? (
                          <TrendingUp
                            size={24}
                            className="text-accent-green"
                          />
                        ) : (
                          <TrendingDown
                            size={24}
                            className="text-accent-red"
                          />
                        )}
                      </div>

                      <div>

                        <div className="flex items-center gap-2">
                          <span className="text-white font-bold text-lg">
                            {item.symbol}
                          </span>

                          <span
                            className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                              isUp
                                ? 'bg-accent-green/10 text-accent-green'
                                : 'bg-accent-red/10 text-accent-red'
                            }`}
                          >
                            {item.prediction}
                          </span>
                        </div>

                        <p className="text-xs text-slate-500 mt-1">
                          {formatDate(item.created_at)}
                        </p>

                      </div>

                    </div>

                    {/* Confidence + Model */}
                    <div className="flex flex-wrap gap-6">

                      <div>
                        <p className="text-xs text-slate-500">
                          Confidence
                        </p>

                        <p className="text-white font-semibold mt-1">
                          {formatNumber(item.confidence)}%
                        </p>
                      </div>

                      <div>
                        <p className="text-xs text-slate-500">
                          Model
                        </p>

                        <div className="flex items-center gap-1.5 mt-1">
                          <Brain
                            size={14}
                            className="text-accent-blue"
                          />

                          <p className="text-white font-medium">
                            {item.model || 'Random Forest'}
                          </p>
                        </div>
                      </div>

                    </div>

                  </div>

                  {/* Technical features */}
                  <div className="mt-5 pt-5 border-t border-white/5">

                    <div className="flex items-center gap-2 mb-4">
                      <BarChart3
                        size={16}
                        className="text-slate-400"
                      />

                      <p className="text-xs font-semibold text-slate-400">
                        Technical Indicators
                      </p>
                    </div>

                    <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-5 gap-4">

                      <div>
                        <p className="text-xs text-slate-500">
                          Close
                        </p>

                        <p className="text-white font-medium mt-1">
                          ₹{formatNumber(features.close)}
                        </p>
                      </div>

                      <div>
                        <p className="text-xs text-slate-500">
                          SMA 20
                        </p>

                        <p className="text-white font-medium mt-1">
                          ₹{formatNumber(features.sma_20)}
                        </p>
                      </div>

                      <div>
                        <p className="text-xs text-slate-500">
                          EMA 20
                        </p>

                        <p className="text-white font-medium mt-1">
                          ₹{formatNumber(features.ema_20)}
                        </p>
                      </div>

                      <div>
                        <p className="text-xs text-slate-500">
                          RSI 14
                        </p>

                        <p className="text-white font-medium mt-1">
                          {formatNumber(features.rsi_14)}
                        </p>
                      </div>

                      <div>
                        <p className="text-xs text-slate-500">
                          Volume
                        </p>

                        <div className="flex items-center gap-1.5 mt-1">
                          <Activity
                            size={13}
                            className="text-slate-400"
                          />

                          <p className="text-white font-medium">
                            {formatNumber(features.volume, 0)}
                          </p>
                        </div>
                      </div>

                    </div>

                  </div>

                </div>
              )
            })}

          </div>

        )}

      </div>

    </div>
  )
}
